apiVersion: v1
kind: Namespace
metadata:
  name: {{ required "namespace.name is required" .Values.namespace.name }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace.name }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
