apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-ldap-sync-config" .Release.Name }}
  namespace: {{ .Values.namespace.name }}
data:
  sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: {{ .Values.ldap.url }}
    insecure: {{ .Values.ldap.insecure }}
    bindDN: {{ .Values.ldap.bindDN }}
    bindPassword:
      file: /etc/ldap-bind/password
    rfc2307:
      groupsQuery:
        baseDN: {{ .Values.ldap.groupsBaseDN | quote }}
        scope: sub
        filter: {{ printf "(cn=%s)" .Values.ldap.groupName | quote }}
      groupUIDAttribute: dn
      groupNameAttributes: [cn]
      groupMembershipAttributes: [{{ .Values.ldap.groupMemberAttribute }}]
      usersQuery:
        baseDN: {{ .Values.ldap.usersBaseDN | quote }}
        scope: sub
      userUIDAttribute: dn
      userNameAttributes: [{{ .Values.ldap.userNameAttribute }}]
  whitelist.txt: |
    {{ printf "cn=%s,%s" .Values.ldap.groupName .Values.ldap.groupsBaseDN }}
